sonar.organization=iamsamflo
sonar.projectKey=iAmSamFlo_devops_course-demo
sonar.sources=app.py
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**